In [2]:
import numpy as np
from PIL import Image as im
  
# define a main function
def main():

   
    array = np.arange(0, 737280, 1, np.uint8)

    print(type(array))

    print(array.shape)
      
   
    array = np.reshape(array, (1024, 720))
      
    # show the shape of the array
    print(array.shape)
  
    # show the array
    print(array)
      
    # creating image object of
    # above array
    data = im.fromarray(array)

    data.save('gfg_dummy_pic.png')
  
# driver code
if __name__ == "__main__":

  main()

<class 'numpy.ndarray'>
(737280,)
(1024, 720)
[[  0   1   2 ... 205 206 207]
 [208 209 210 ... 157 158 159]
 [160 161 162 ... 109 110 111]
 ...
 [144 145 146 ...  93  94  95]
 [ 96  97  98 ...  45  46  47]
 [ 48  49  50 ... 253 254 255]]


In [3]:
from PIL import Image
import numpy as np
# Creating the 144 X 144 NumPy Array with random values
arr = np.random.randint(255, size=(144, 144), dtype=np.uint8)
# Converting the numpy array into image
img  = Image.fromarray(arr)
# Saving the image
img.save("Image_from_array.png")
print(" The Image is saved successfully")
img.show()

 The Image is saved successfully


In [5]:
from PIL import Image
import os
os.getcwd()

'C:\\Users\\User\\Image processing'

In [6]:
os.listdir()

['.ipynb_checkpoints',
 '1.jpg',
 '10.jpg',
 '11.png',
 '17.jpg',
 '1img.jpg',
 '2.jpg',
 '20.jfif',
 '2img.jpg',
 'a.jpg',
 'Adding one to another.ipynb',
 'b.jpg',
 'back.jpg',
 'Basic statistics.ipynb',
 'bird.jpg',
 'bird.png',
 'Bitwise.ipynb',
 'black.jfif',
 'Blending.ipynb',
 'Canvas.ipynb',
 'cat1.png',
 'cat_damaged.png',
 'cat_inpainted.png',
 'cat_mask.png',
 'Contour lines.ipynb',
 'Contours.ipynb',
 'converted.png',
 'converting and mode.ipynb',
 'crop.ipynb',
 'crop.png',
 'cropped.jpg',
 'cropped_image.jpg',
 'd1.jpg',
 'd2.jpg',
 'damaged.jpg',
 'dice.png',
 'Difference in images.ipynb',
 'dog.jfif',
 'drawing and text.ipynb',
 'earth.jfif',
 'face.jpg',
 'flight.jpg',
 'flr.jpg',
 'fore.png',
 'gfg_dummy_pic.png',
 'Image invert.ipynb',
 'Image manipulation.ipynb',
 'Image Restoration.ipynb',
 'Image_from_array.png',
 'imgf.jpg',
 'imgface.jpg',
 'imgffc.png',
 'Intensity transformation.ipynb',
 'interpolation.ipynb',
 'kit.jpg',
 'leaf.png',
 'lg.png',
 'List and dis

In [7]:
for f in os.listdir("."):
    if f.endswith(".jpg"):
        i = Image.open(f)
        fn, fext = os.path.splitext(f)
        print(fn, "&", fext)

1 & .jpg
10 & .jpg
17 & .jpg
1img & .jpg
2 & .jpg
2img & .jpg
a & .jpg
b & .jpg
back & .jpg
bird & .jpg
cropped & .jpg
cropped_image & .jpg
d1 & .jpg
d2 & .jpg
damaged & .jpg
face & .jpg
flight & .jpg
flr & .jpg
imgf & .jpg
imgface & .jpg
kit & .jpg
log & .jpg
nature & .jpg
new & .jpg
original_image & .jpg
sharpen & .jpg
sky1 & .jpg
slicing & .jpg
taj & .jpg
text & .jpg
text_removed_image & .jpg
watermark & .jpg


In [8]:
for f in os.listdir("."):
    if f.endswith(".jpg"):
        print(f)

1.jpg
10.jpg
17.jpg
1img.jpg
2.jpg
2img.jpg
a.jpg
b.jpg
back.jpg
bird.jpg
cropped.jpg
cropped_image.jpg
d1.jpg
d2.jpg
damaged.jpg
face.jpg
flight.jpg
flr.jpg
imgf.jpg
imgface.jpg
kit.jpg
log.jpg
nature.jpg
new.jpg
original_image.jpg
sharpen.jpg
sky1.jpg
slicing.jpg
taj.jpg
text.jpg
text_removed_image.jpg
watermark.jpg


In [11]:
# Creating new Directory using OS library
os.mkdir('NewExtnsn')

In [12]:
for f in os.listdir("."):
    if f.endswith(".jpg"):
        i = Image.open(f)
        fn, fext = os.path.splitext(f)
        i.save("NewExtnsn/{}.pdf".format(fn))

In [13]:
# Creating new multiple Directories using OS library
os.makedirs('resize//small')
os.makedirs('resize//tiny')
# Note: If you already have a directory with this name, you will get error.
size_small = (600,600) # small images of 600 X 600 pixels
size_tiny = (200,200)  # tiny images of 200 X 200 pixels
for f in os.listdir("."):
    if f.endswith(".jpg"):
        i = Image.open(f)
        fn, fext = os.path.splitext(f)
        i.thumbnail(size_small)
        i.save("resize/small/{}_small{}".format(fn, fext))
        i.thumbnail(size_tiny)
        i.save("resize/tiny/{}_tiny{}".format(fn, fext))

In [14]:
# Creating new Directory using OS library
os.mkdir('rotate')
for f in os.listdir("."):
    if f.endswith(".jpg"):
        i = Image.open(f)
        fn, fext = os.path.splitext(f)
        im = i.rotate(90)
        im.save("rotate/{}_rot.{}".format(fn, fext))